// Generated by CoffeeScript 1.6.3
var app, exports, express, passport;

express = require('express');

passport = require('passport');

app = express();

app.use(express.bodyParser());

app.use(passport.initialize());

exports = module.exports = app;
