// Generated by CoffeeScript 1.6.3
var restify, server;

restify = require('restify');

server = restify.createServer({
  name: 'peacemakers-api'
});

server.pre(restify.pre.userAgentConnection());

server.get('/api/:name', function(req, res, next) {
  return res.send('Hello ' + req.params.name);
});

server.listen(8080, function() {
  return console.log('%s listening at %s', server.name, server.url);
});
