// Generated by CoffeeScript 1.6.3
var app, auth, config, env, express, mongoose, passport, permissions, roles, schools, users;

env = process.env.NODE_ENV || 'development';

config = require('./config/config')[env];

mongoose = require('mongoose');

mongoose.connect(config.db);

require('./models/user');

require('./models/school');

passport = require('passport');

require('./config/passport')(passport, config);

express = require('express');

app = express();

app.use(express.bodyParser());

app.use(passport.initialize());

auth = require('./modules/auth')(app, config);

permissions = require('./modules/permissions')(app, config);

roles = require('./modules/roles')(app, config);

users = require('./modules/users')(app, config);

schools = require('./modules/schools')(app);

app.listen(3000);

console.log("Listening on port 3000...");
