// Generated by CoffeeScript 1.6.3
var Permission, app, mongoose, should;

mongoose = require("mongoose");

should = require("should");

app = require("../app/server");

Permission = mongoose.model('Permission');

describe("Permission Model", function() {
  beforeEach(function(done) {
    return mongoose.connection.db.dropCollection("permissions", done());
  });
  it("should register a new Permission", function(done) {
    var permission;
    permission = new Permission({
      subject: "Schools",
      action: "create",
      displayName: "Create new School",
      description: "Description to create a new School."
    });
    return permission.save(done);
  });
  return afterEach(function(done) {
    return mongoose.connection.db.dropCollection("permissions", done());
  });
});
