// Generated by CoffeeScript 1.6.3
var Permission, Role, app, mongoose, should;

mongoose = require("mongoose");

should = require("should");

app = require("../app/server");

Permission = mongoose.model('Permission');

Role = mongoose.model('Role');

describe("Role Model", function() {
  var _this = this;
  before(function(done) {
    var p, permission, permissions, _i, _len;
    permissions = [
      {
        subject: "Schools",
        action: "create",
        displayName: "Create new School",
        description: "Description to create a new School."
      }, {
        subject: "Schools",
        action: "edit",
        displayName: "Edit a School",
        description: "Description to edit a new School."
      }, {
        subject: "Schools",
        action: "destroy",
        displayName: "Destroy a School",
        description: "Description to destroy a School."
      }
    ];
    for (_i = 0, _len = permissions.length; _i < _len; _i++) {
      p = permissions[_i];
      permission = new Permission(p);
      permission.save(function(err) {
        if (err) {
          return done(err);
        }
      });
    }
    return done();
  });
  it("should register a new Role", function(done) {
    _this.role = new Role({
      name: "admin",
      displayName: "Admin",
      description: "Site Administrator"
    });
    return _this.role.save(function(err) {
      should.not.exist(err);
      return done();
    });
  });
  it("should add a new valid Permission to the Role", function(done) {
    var permission;
    permission = {
      subject: 'Schools',
      action: 'edit'
    };
    return _this.role.addPermission(permission, function(err) {
      should.not.exist(err);
      return _this.role.save(function(err) {
        should.not.exist(err);
        _this.role.permissions.should.have.lengthOf(1);
        return done();
      });
    });
  });
  it("should not add a new invalid Permission to the Role", function(done) {
    var permission;
    permission = {
      subject: 'XXX',
      action: 'edit'
    };
    return _this.role.addPermission(permission, function(err) {
      should.exist(err);
      _this.role.permissions.should.have.lengthOf(1);
      return done();
    });
  });
  it("should not add duplicated Permissions", function(done) {
    var permission;
    permission = {
      subject: 'Schools',
      action: 'edit'
    };
    return _this.role.addPermission(permission, function(err) {
      should.exist(err);
      _this.role.permissions.should.have.lengthOf(1);
      return done();
    });
  });
  return after(function(done) {
    return mongoose.connection.db.dropCollection("roles", function(err) {
      if (err) {
        done(err);
      }
      return mongoose.connection.db.dropCollection("permissions", function(err) {
        if (err) {
          done(err);
        }
        return done();
      });
    });
  });
});
