// Generated by CoffeeScript 1.6.3
var Role, mongoose;

mongoose = require('mongoose');

Role = mongoose.model('Role');

exports.list = function(req, res) {
  console.log("GET: ");
  console.log(req.query);
  console.log(req.authInfo);
  return Role.find().exec(function(err, roles) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    return res.send(roles);
  });
};

exports.create = function(req, res) {
  var role;
  console.log("POST: ");
  console.log(req.body);
  role = new Role(req.body);
  return role.save(function(err) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    console.log("created");
    return res.send(role);
  });
};

exports.addPermission = function(req, res) {
  console.log("Role: " + req.params.id);
  console.log("POST: ");
  console.log(req.body);
  return Role.findById(req.params.id, function(err, role) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    if (!role) {
      console.log(err);
      res.statusCode = 404;
      return res.send("Error 404: Resource not found!");
    }
    return role.addPermission(req.body, function(err) {
      if (err) {
        console.log(err);
        res.statusCode = 500;
        return res.send("Error 500: Internal Server Error found!");
      }
      return role.save(function(err) {
        if (err) {
          console.log(err);
          res.statusCode = 500;
          return res.send("Error 500: Internal Server Error found!");
        }
        console.log("permission added to role");
        return res.send(role);
      });
    });
  });
};
