// Generated by CoffeeScript 1.6.3
var User, mongoose;

mongoose = require('mongoose');

User = mongoose.model('User');

exports.list = function(req, res) {
  console.log("GET: ");
  console.log(req.query);
  console.log(req.authInfo);
  return User.find().exec(function(err, users) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    return res.send(users);
  });
};

exports.create = function(req, res) {
  var user;
  console.log("POST: ");
  console.log(req.body);
  user = new User(req.body);
  return user.save(function(err) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    console.log("created");
    return res.send(user);
  });
};

exports.addRole = function(req, res) {
  console.log("User: " + req.params.id);
  console.log("POST: ");
  console.log(req.body);
  return User.findById(req.params.id, function(err, user) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    if (!user) {
      console.log(err);
      res.statusCode = 404;
      return res.send("Error 404: Resource not found!");
    }
    return user.addRole(req.body.roleName, function(err) {
      if (err) {
        console.log(err);
        res.statusCode = 500;
        return res.send("Error 500: Internal Server Error found!");
      }
      return user.save(function(err) {
        if (err) {
          console.log(err);
          res.statusCode = 500;
          return res.send("Error 500: Internal Server Error found!");
        }
        console.log("role added to user");
        return res.send(user);
      });
    });
  });
};
