// Generated by CoffeeScript 1.6.3
var User, mongoose;

mongoose = require('mongoose');

User = mongoose.model('User');

exports.restrictTo = function(subject, action) {
  return function(req, res, next) {
    return User.findById(req.user._id, function(err, user) {
      if (err) {
        next(err);
      }
      return user.can(subject, action, function(err, has) {
        if (err) {
          next(err);
        }
        if (!has) {
          res.statusCode = 403;
          return res.send("Error 403: Forbidden!");
          next();
        }
        return next();
      });
    });
  };
};
