// Generated by CoffeeScript 1.6.3
var passport, permisions;

passport = require("passport");

permisions = require('./permissions');

module.exports = function(app, config) {
  var bearer;
  bearer = passport.authenticate('bearer', {
    session: false
  });
  app.get('/api/permissions', permisions.list);
  return app.post('/api/permissions', permisions.create);
};
