// Generated by CoffeeScript 1.6.3
var Permission, mongoose;

mongoose = require('mongoose');

Permission = mongoose.model('Permission');

exports.list = function(req, res) {
  console.log("GET: ");
  console.log(req.query);
  console.log(req.authInfo);
  return Permission.find().exec(function(err, permissions) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    return res.send(permissions);
  });
};

exports.create = function(req, res) {
  var permission;
  console.log("POST: ");
  console.log(req.body);
  permission = new Permission(req.body);
  permission.save(function(err) {
    if (err) {
      console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
    return console.log("created");
  });
  return res.send(permission);
};
