// Generated by CoffeeScript 1.6.3
var School, mongoose, passport;

passport = require('passport');

mongoose = require('mongoose');

School = mongoose.model('School');

exports.list = function(req, res) {
  console.log("GET: ");
  console.log(req.query);
  return School.find().exec(function(err, schools) {
    if (!err) {
      return res.send(schools);
    } else {
      return console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
  });
};

exports.show = function(req, res) {
  console.log("GET: " + req.params.id);
  return School.findById(req.params.id, function(err, school) {
    if (!err) {
      if (school) {
        return res.send(school);
      } else {
        console.log("Resource not found!");
        res.statusCode = 400;
        return res.send("Error 400: Resource not found!");
      }
    } else {
      return console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
  });
};

exports.create = function(req, res) {
  var school;
  console.log("POST: ");
  console.log(req.body);
  school = new School(req.body);
  school.save(function(err) {
    if (!err) {
      return console.log("created");
    } else {
      return console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
  });
  return res.send(school);
};

exports.update = function(req, res) {
  console.log("PUT: " + req.params.id);
  return School.findById(req.params.id, function(err, school) {
    if (!err) {
      if (school) {
        school.name = req.body.name;
        school.www = req.body.www;
        return school.save(function(err) {
          if (!err) {
            console.log("updated");
          } else {
            console.log(err);
            res.statusCode = 500;
            return res.send("Error 500: Internal Server Error found!");
          }
          return res.send(school);
        });
      } else {
        console.log("Resource not found!");
        res.statusCode = 400;
        return res.send("Error 400: Resource not found!");
      }
    } else {
      return console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
  });
};

exports.destroy = function(req, res) {
  console.log("DELETE: " + req.params.id);
  return School.findById(req.params.id, function(err, school) {
    if (!err) {
      if (school) {
        return school.remove(function(err) {
          if (!err) {
            console.log("removed");
            return res.send('');
          } else {
            console.log(err);
            res.statusCode = 500;
            return res.send("Error 500: Internal Server Error found!");
          }
        });
      } else {
        console.log("Resource not found!");
        res.statusCode = 400;
        return res.send("Error 400: Resource not found!");
      }
    } else {
      return console.log(err);
      res.statusCode = 500;
      return res.send("Error 500: Internal Server Error found!");
    }
  });
};
